### ISSUE TITLE
不能监听打开或者关闭动画周期吗

### ISSUE THREAD

**Issue by rmtic** [ruzhan123/ViewHolder-Slide-Helper#2]

**Comment by ruzhan123** [comment]
@rmtic 

@Override public void doAnimationSet(int offset, float fraction) {

复写这是方法，每一次动画周期的每一帧都会回调

**Comment by rmtic** [comment]
我是在adapter中标志boolean enableModify = false/true,每次切换模式，我都会调用notifyDataSetChanged();不知道怎么动画结束后在调用notifyDataSetChanged();

**Comment by ruzhan123** [comment]
@rmtic 我更新一下库，稍等30分种左右，之前写的比较仓促，没有注意到一些细节

**Comment by ruzhan123** [comment]
@rmtic 

版本更新至v1.1
`compile 'com.github.ruzhan123:ViewHolder-Slide-Helper:v1.1'`

关于需要监听到打开关闭状态，你需要在viewHolder设置：
`        setSlideAnimatorListener(new SlideAnimatorListener() {
            @Override
            public void onSlideAnimationStart(Animator animation, int currentStatus) {
                Log.i(TAG, "setSlideAnimatorListener: onSlideAnimationStart: "
                        + (currentStatus == SlideAnimationHelper.STATE_OPEN ? "open" : "close"));
            }

            @Override
            public void onSlideAnimationEnd(Animator animation, int currentStatus) {
                Log.i(TAG, "setSlideAnimatorListener: onSlideAnimationEnd: "
                        + (currentStatus == SlideAnimationHelper.STATE_OPEN ? "open" : "close"));
            }
        });`

具体可以看demo中的OneSlideViewHolder

希望能帮助到你

**Comment by rmtic** [comment]
谢谢你🙏

**Comment by rmtic** [comment]
1.1后，动画效果好像不能了

**Comment by ruzhan123** [comment]
@rmtic 我这边demo是正常的

**Comment by ruzhan123** [comment]
@rmtic v1.2滚动时，打开或者关闭动画有问题，v1.3修复了。之前想做性能优化，view销毁时关闭动画，recyclerview滚动时动态回收view的，导致动画执行一半被cancel掉了
