### ISSUE TITLE
SlideAnimationHelper的mCurrentState是静态变量

### ISSUE THREAD

**Issue by hanamimayoi** [ruzhan123/ViewHolder-Slide-Helper#3]
因为是静态变量，退出界面再进的话，还是保持open状态

**Comment by hanamimayoi** [comment]
是我看疏忽了，是用静态变量来控制onBindViewHolder的open或者close状态，但是静态变量会导致下一次进入界面还是保持上一次退出时的状态

**Comment by ruzhan123** [comment]
@hanamimayoi 这个可以自己控制修改的，静态变量我是写demo方便处理的
